"""empty message

Revision ID: 344ab2859c1f
Revises: 0e37d43eba22
Create Date: 2022-10-12 18:29:56.173407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344ab2859c1f'
down_revision = '0e37d43eba22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_page', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user_role', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'id')
    op.drop_column('user', 'full_name')
    op.drop_column('role_page', 'id')
    # ### end Alembic commands ###
