"""empty message

Revision ID: 552bc011e5ce
Revises: b9e5b07cdff3
Create Date: 2022-10-30 14:03:16.919144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552bc011e5ce'
down_revision = 'b9e5b07cdff3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laporan', sa.Column('alamat', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laporan', 'alamat')
    # ### end Alembic commands ###
