"""empty message

Revision ID: 9f3f73f7fd6e
Revises: 552bc011e5ce
Create Date: 2022-11-12 21:42:55.089317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3f73f7fd6e'
down_revision = '552bc011e5ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengumuman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('isi', sa.Text(), nullable=True),
    sa.Column('gambar', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.Column('created_at_epoch_utc', sa.Integer(), nullable=False),
    sa.Column('updated_at_epoch_utc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('komentar_pengumuman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('isi', sa.Text(), nullable=True),
    sa.Column('pengumuman_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at_epoch_utc', sa.Integer(), nullable=False),
    sa.Column('updated_at_epoch_utc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pengumuman_id'], ['pengumuman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('komentar_pengumuman')
    op.drop_table('pengumuman')
    # ### end Alembic commands ###
