FROM node:16-alpine as build-step

WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json

RUN npm install

COPY . /usr/src/app
RUN npm run build --production

EXPOSE 3000
WORKDIR /app
COPY --from=builder /usr/src/app .

CMD ["npm", "start"]
