name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-hub-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push client to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: vilage-system/client:v${{github.run_number}}
      - name: Build and push api to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: vilage-system/api:v${{github.run_number}}
      - name: Build and push db to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./db
          push: true
          tags: vilage-system/db:v${{github.run_number}}