version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/usr/src/app'
      - '/usr/src/app/node_modules'
    container_name: client-react-ui
    stdin_open: true
    networks:
      - nginx_network
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - api
      - client
    networks:
      - nginx_network
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    environment:
      - DATABASE_URL_ENV=${DATABASE_URL}
    depends_on:
      dtpl-db:
        condition: service_healthy
    volumes:
      - ./api:/api
    networks:
      - nginx_network
  dtpl-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    networks:
      - nginx_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nginx_network:
    driver: bridge
