name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker-hub-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push client to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./client
          file: ./client/Dockerfile-prod
          push: true
          tags: agasyan/vilage-system-client:latest, agasyan/vilage-system-client:v${{github.run_number}}
      - name: Build and push api to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./api
          push: true
          tags: agasyan/vilage-system-api:latest, agasyan/vilage-system-api:v${{github.run_number}}
      - name: Build and push db to dockerhub
        uses: docker/build-push-action@v3
        with:
          context: ./db
          push: true
          tags: agasyan/vilage-system-db:latest, agasyan/vilage-system-db:v${{github.run_number}}
  deploy-digital-ocean:
    needs: docker-hub-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Init directory
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            mkdir -p village-system
      - name: Init .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_PG_USER: ${{ secrets.PG_USER }}
          envkey_PG_PASS: ${{ secrets.PG_PASS }}
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NGINX_HTTPS_URL: ${{ secrets.NGINX_HTTPS_URL }}
          Envkey_NGINX_HTTPS_EMAIL: ${{ secrets.NGINX_HTTPS_EMAIL }}
          envkey_API_IMAGE: ${{ secrets.API_IMAGE }}
          envkey_CLIENT_IMAGE: ${{ secrets.CLIENT_IMAGE }}
          envkey_DB_IMAGE: ${{ secrets.DB_IMAGE }}
      - name: Copy file via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          source: "docker-compose.prod.yml,.env"
          target: "village-system"
